//
//  AppDelegate.h
//
// Stock file generated by Xcode. 
// You do not need this file to use the popup control in your own project.
//

#import <UIKit/UIKit.h>

@interface AppDelegate : UIResponder <UIApplicationDelegate>

@property (strong, nonatomic) UIWindow *window;

@end
